# Generated by Django 5.1.4 on 2024-12-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_alter_donor_referral_code_alter_donor_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_donors', to='donations.donor'),
        ),
    ]
